// Re-export all IPC types from the canonical shared location.
// Renderer components import from here for convenience.
export type {
  Unsubscribe,
  Installation,
  RunningInstance,
  Source,
  SourceField,
  FieldOption,
  DetailSection,
  DetailItem,
  DetailField,
  DetailFieldOption,
  ActionDef,
  ConfirmDef,
  ConfirmOption,
  FieldSelectDef,
  SelectDef,
  PromptDef,
  ListAction,
  ActionResult,
  PortConflictInfo,
  AddResult,
  KillResult,
  SettingsSection,
  SettingsAction,
  SettingsField,
  ModelsResult,
  ModelsSection,
  ModelsField,
  ProbeResult,
  ProgressData,
  ProgressStep,
  ComfyOutputData,
  ComfyExitedData,
  GPUInfo,
  HardwareValidation,
  NvidiaDriverCheck,
  DiskSpaceInfo,
  PathIssue,
  UpdateInfo,
  UpdateDownloadProgress,
  TrackResult,
  ElectronApi,
} from '../../../types/ipc'
