import path from 'path'
import fs from 'fs'
import { dataDir } from './paths'
import { writeFileSafe } from './safe-file'

// Canonical ComfyUI model folder types from folder_paths.py.
// When ComfyUI adds `all_model_folders` support in extra_model_paths.yaml,
// this list can be replaced with a single `all_model_folders: true` flag.
export const MODEL_FOLDER_TYPES = [
  "checkpoints",
  "classifiers",
  "clip_vision",
  "configs",
  "controlnet",
  "diffusers",
  "diffusion_models",
  "embeddings",
  "gligen",
  "hypernetworks",
  "latent_upscale_models",
  "loras",
  "model_patches",
  "audio_encoders",
  "photomaker",
  "style_models",
  "text_encoders",
  "upscale_models",
  "vae",
  "vae_approx",
] as const

const YAML_PATH: string = path.join(dataDir(), "shared_model_paths.yaml")

function buildYaml(modelsDirs: string[]): string {
  const lines = [
    "# Generated by ComfyUI Desktop 2.0 — do not edit manually.",
    "# When ComfyUI supports all_model_folders, this file will be simplified to:",
    "#   comfyui_desktop_2:",
    "#     base_path: '...'",
    "#     is_default: true",
    "#     all_model_folders: true",
    "",
  ]
  modelsDirs.forEach((dir, i) => {
    const escaped = dir.replace(/'/g, "''")
    lines.push(`comfyui_desktop_2_${i}:`)
    lines.push(`  base_path: '${escaped}'`)
    if (i === 0) lines.push("  is_default: true")
    for (const folder of MODEL_FOLDER_TYPES) {
      lines.push(`  ${folder}: ${folder}/`)
    }
    lines.push("")
  })
  return lines.join("\n")
}

/**
 * Ensures the shared model paths YAML is up to date.
 * Returns the path to the YAML file, or null if no directories are configured.
 */
export function ensureModelPathsConfig(modelsDirs: string[] | null | undefined): string | null {
  if (!modelsDirs || !Array.isArray(modelsDirs) || modelsDirs.length === 0) return null
  const resolved = modelsDirs.map((d) => path.resolve(d))
  const yaml = buildYaml(resolved)

  let existing: string | null = null
  try {
    existing = fs.readFileSync(YAML_PATH, "utf-8")
  } catch {}

  if (existing !== yaml) {
    writeFileSafe(YAML_PATH, yaml)
  }

  return YAML_PATH
}
