const path = require("path");
const fs = require("fs");
const { app } = require("electron");

// Canonical ComfyUI model folder types from folder_paths.py.
// When ComfyUI adds `all_model_folders` support in extra_model_paths.yaml,
// this list can be replaced with a single `all_model_folders: true` flag.
const MODEL_FOLDER_TYPES = [
  "checkpoints",
  "classifiers",
  "clip_vision",
  "configs",
  "controlnet",
  "diffusers",
  "diffusion_models",
  "embeddings",
  "gligen",
  "hypernetworks",
  "latent_upscale_models",
  "loras",
  "model_patches",
  "audio_encoders",
  "photomaker",
  "style_models",
  "text_encoders",
  "upscale_models",
  "vae",
  "vae_approx",
];

const YAML_PATH = path.join(app.getPath("userData"), "shared_model_paths.yaml");

function buildYaml(modelsDirs) {
  const lines = [
    "# Generated by ComfyUI Launcher — do not edit manually.",
    "# When ComfyUI supports all_model_folders, this file will be simplified to:",
    "#   comfyui_launcher:",
    "#     base_path: '...'",
    "#     is_default: true",
    "#     all_model_folders: true",
    "",
  ];
  modelsDirs.forEach((dir, i) => {
    const escaped = dir.replace(/'/g, "''");
    lines.push(`comfyui_launcher_${i}:`);
    lines.push(`  base_path: '${escaped}'`);
    if (i === 0) lines.push("  is_default: true");
    for (const folder of MODEL_FOLDER_TYPES) {
      lines.push(`  ${folder}: ${folder}/`);
    }
    lines.push("");
  });
  return lines.join("\n");
}

/**
 * Ensures the shared model paths YAML is up to date.
 * Returns the path to the YAML file, or null if no directories are configured.
 */
function ensureModelPathsConfig(modelsDirs) {
  if (!modelsDirs || !Array.isArray(modelsDirs) || modelsDirs.length === 0) return null;
  const resolved = modelsDirs.map((d) => path.resolve(d));
  const yaml = buildYaml(resolved);

  let existing = null;
  try {
    existing = fs.readFileSync(YAML_PATH, "utf-8");
  } catch {}

  if (existing !== yaml) {
    const tmpPath = YAML_PATH + ".tmp";
    fs.mkdirSync(path.dirname(YAML_PATH), { recursive: true });
    fs.writeFileSync(tmpPath, yaml);
    fs.renameSync(tmpPath, YAML_PATH);
  }

  return YAML_PATH;
}

module.exports = { ensureModelPathsConfig, MODEL_FOLDER_TYPES };
